# Generated by Django 4.2.11 on 2024-03-25 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='devicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('type', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=250)),
                ('Department', models.CharField(max_length=250)),
                ('BusinessUnit', models.CharField(choices=[('1', 'sales'), ('2', 'Delivery'), ('3', 'Warehouse')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.branch')),
            ],
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MacAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('SerialNo', models.CharField(blank=True, max_length=250, null=True)),
                ('MobileNo', models.TextField()),
                ('ScreenProtector', models.BooleanField(default=False)),
                ('Cover', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Damaged'), ('3', 'Dead')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.devicetype')),
            ],
        ),
    ]
