# Generated by Django 4.2.11 on 2024-03-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='ScreenProtector',
        ),
        migrations.AlterField(
            model_name='devices',
            name='MacAddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='MobileNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='devices',
            name='SerialNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
