# Generated by Django 4.2.11 on 2024-03-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_remove_devices_screenprotector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Damaged'), ('D', 'Dead')], default='A', max_length=1),
        ),
    ]
