# Generated by Django 4.2.11 on 2024-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_remove_employees_businessunit_alter_devices_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(choices=[('sales', 'Sales'), ('delivery', 'Delivery'), ('warehouse', 'Warehouse')], max_length=20),
        ),
    ]
