# Generated by Django 4.2.11 on 2024-03-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_alter_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Damaged', 'Damaged'), ('Dead', 'Dead')], default='A', max_length=10),
        ),
    ]
