# Generated by Django 4.2.11 on 2024-03-29 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_alter_devicetype_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.devices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.employees')),
            ],
        ),
    ]
